### ISSUE TITLE
Missing .obj files for Schunk WSG 50

### ISSUE THREAD

**Issue by markisus** [mpetersen94/mp-gcs#47]
Hi, I'm new to Drake. I installed it with `pip install drake` within the same virutalenv that I'm using for the gcs repo. I and tried to run the `prm_comparison` notebook. One of the cells failed with `RuntimeError: /home/mark/gcs/models/schunk_wsg_50_welded_fingers.sdf:5: error: URI 'package://drake/manipulation/models/wsg_50_description/meshes/wsg_body.obj' resolved to '/home/mark/gcs/env/lib/python3.8/site-packages/pydrake/share/drake/manipulation/models/wsg_50_description/meshes/wsg_body.obj' which does not exist`  

Do I have to download this .obj (and others) separately? Where can I find these? Thanks!

Additional Info: I did not recompile the patched branch mentioned in the readme since I don't actually care about the PRM code. I just want to play around with the CGS planning for manipulation. In the notebook I'm just commenting out all the code related to PRM.

**Comment by TobiaMarcucci** [comment]
Thanks for letting us know! @wrangelvid Can you help with this?

**Comment by wrangelvid** [comment]
The `prm_comparison_update` branch has the changes that fix the issue. It will be merged soon into the main branch once a few necessary changes land in drake master.

**Comment by TobiaMarcucci** [comment]
Let's keep this open then, and close it when the changes land

**Comment by wrangelvid** [comment]
Landed fix. #49
